### ISSUE TITLE
cool plugin except it is rounding the answer

### ISSUE THREAD

**Issue by cphoover** [Pephers/Super-Calculator#1]
cool plugin except 10/3 is not equal to 3 . Anyway to have it round off after a certain number of decimal points instead?

**Comment by Pephers** [comment]
Hi cphoover

Thanks for your report and thanks for using my plugin. You're right, division was rounded down. This was due to Python 2.x on which ST2 is built by default rounds down using `floor`. This is being changed in Python 3.x but can be fixed by importing the 3.x division definition into version 2.x, see: http://docs.python.org/release/2.2.3/whatsnew/node7.html

I have fixed this issue so you may update your plugin or let Package Control do it for you. Right now it is rounding down to 2 decimals but I can make a setting for it if wanted.

/Pephers
